algoritmo "Sum_two_numbers"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   n1, n2, sum: inteiro
inicio
      Escreva("Digite um número: ")
      Leia(n1)
      Escreva("Digite outro número: ")
      Leia(n2)
      sum <- n1 + n2
      Escreval("A soma entre", n1," e", n2," é", sum)
fimalgoritmo
