algoritmo "Double_number"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   n, d, t: real
inicio

      Escreva("Digite um número: ")
      Leia(n)
      d <- n * 2
      t <- n / 3
      Escreval("O dobro de ", n," é ", d:2:2)
      Escreval("A terça parte de ", n," é ", t:2:4)

fimalgoritmo
