algoritmo "Par_impar"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   n: inteiro
inicio

      Escreva("Digite um número: ")
      Leia(n)
      Se (n % 2 = 0) entao
         Escreval("O número ", n ," é par")
      Senao
           Escreval("O número ", n ," é ímpar")
      Fimse

fimalgoritmo
