algoritmo "Maior_numero"

var
   n1, n2: inteiro
inicio
      Escreval("---------------Comparação numérica---------------")
      Escreva("Digite o 1º valor: ")
      Leia(n1)
      Escreva("Digite o 2º valor: ")
      Leia(n2)
      Se n1 > n2 entao
         Escreval("O primeiro valor é o maior ")
      Senao
           Se n2 > n1 entao
              Escreval("O segundo valor é maior")
           Fimse
      Fimse

fimalgoritmo
