algoritmo "Contador_crescente"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   cont, x: inteiro
inicio
      cont <- 6
      Escreval(cont)
      Enquanto (cont >= 6) e (cont < 11) faca
               cont <- cont + 1
               Escreval(cont)
      Fimenquanto

      Escreval("Acabou!")

fimalgoritmo
