algoritmo "Cont_som_3"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   cont: inteiro
inicio
      cont <- 0
      Escreval(cont)
      Enquanto (cont >= 0) e (cont < 18) faca
               cont <- cont + 3
               Escreval(cont)
      Fimenquanto
      
      Escreval("Acabou!")

fimalgoritmo
