algoritmo "Cont_100_5"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   cont: inteiro
inicio
      cont <- 100
      Escreval(cont)
      Enquanto (cont <= 100) e (cont > 0) faca
               cont <- cont - 5
               Escreval(cont)
      Fimenquanto

      Escreval("Acabou!")

fimalgoritmo
