algoritmo "Cont_3_Estr"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   valor: inteiro
inicio
      valor <- 0
      
      Escreval(valor)
      
      Repita
      
          valor <- valor + 3
          
          Escreval(valor)
          
      Ate(valor >= 30)
      
      Escreval("Acabou!")
      
fimalgoritmo
