algoritmo "Cont_int_user_Pr_usr"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   i, valor: inteiro
inicio
      Escreva("Digite um valor: ")
      Leia(valor)
      
      Para i de 0 ate valor passo 1 faca
       Escreval(i)
      Fimpara
      
      Escreval("Acabou!")
fimalgoritmo
