algoritmo "Vet_rand"
// =============================================================
//
//
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================
var
   vet: vetor[1..7] de inteiro
   i: inteiro
inicio
      Para i de 1 ate 7 passo 1 faca
           RandI(7)
           vet[i] <- RandI(7)
           Escreval(vet[i])
      Fimpara
fimalgoritmo
