algoritmo "Proc_hello-world"
// =============================================================
// Algoritmo para criar um procedimento para imprimir a mensagem:
// olá mundo!
// AUTOR: Vinicius Bayão
// Curso: Algoritmos(Curso em Vídeo)
// =============================================================

var

procedimento Gerador()
Inicio

Escreval("-----------------")
Escreval("Olá Mundo!")
Escreval("-----------------")

Fimprocedimento

inicio

Gerador()

fimalgoritmo
