algoritmo "Proc_paramet_2"

var
   valor: inteiro
   c: caractere
   
Procedimento Gerador(a: caractere; x: inteiro)
var
   i: inteiro
Inicio
      Para i de 1 ate x faca
           Escreval("-------------------------------------")
           Escreval(a)
           Escreval("-------------------------------------")
      Fimpara
Fimprocedimento

inicio

      c <- "Olá mundo!, Estou aprendendo portugol"
      valor <- 4
      Gerador (c, valor)

fimalgoritmo
